added a nexmo.js to the controllers folder
mjrdnk/express-simple pull request #8
Opened 2017-10-12 12:18 UTC by abdullateef97

added a nexmo module to controller, it allows u send sms using the nexmo platform

2017-10-12 12:24 UTC, mjrdnk requested changes
Thank you very much for your contribution @abdullateef97 ! Possible that you create 'Examples' section in README (between Usage and Credits) and move existing example controller to 'Examples' section in README?

2017-10-13 10:59 UTC, mjrdnk requested changes
Please, do the last adoptions:
1. remove code from controller (I would like to keep the files clean - examples only in README),
2. remove changes from package.json (same as above),
3. remove changes from 'usage' section (this section is for express-simple usage),
4. Make sure to keep the same white spaces stylings as in the rest of the project (check files how I used spaces between `() => {}` )

Thanks

2017-10-13 10:59 UTC, mjrdnk commented on controllers/nexmo.js
> +nexmo.prototype.sendSms = (from,toPath,message)=>{
Is it possible to rewrite these methods in the way to avoid .prototype? 
Thanks!

2017-10-13 10:59 UTC, mjrdnk commented on controllers/nexmo.js
> +            this.nex.message.sendSms(from, to, message, (err,responseData)=>{
make sure you are using single spaces between 
```
)=>{
```
 
so it becomes 
```
) => {
```

Just for the sake of the same style all around the project.

2017-10-13 11:05 UTC, abdullateef97 commented
@mjrdnk where do i add the usage

2017-10-13 11:10 UTC, abdullateef97 commented on controllers/nexmo.js
> +nexmo.prototype.sendSms = (from,toPath,message)=>{
i already did that

2017-10-13 11:10 UTC, abdullateef97 commented on controllers/nexmo.js
> +nexmo.prototype.sendSms = (from,toPath,message)=>{
where do i add the usage

2017-10-13 11:13 UTC, mjrdnk commented
For usage write a snippet for server.js and route for this controller.
So **only** in README file we need something like this:

**Examples:**

Example: nexmo - sms service 
To write your custom controllers write your functions in the file and export the module:

```
here goes controller for nexmo
```

so the controller could be reused in router file nexmo.route.js, like this (please check other helloWorld route for implementation): 

```
here goes route for nexmo
```

In order to use it in your app you have to declare it in the server.js, like this:
```
...
let API_BASE = config.API_BASE;
let helloWorld = require('./routes/helloWorld.js');
let nexmo = require('./routes/nexmo.route.js');

app.use(function(req, res, next) {
...

...

}));

app.use(API_BASE, helloWorld);
app.use(API_BASE, nexmo);

app.listen(port, function() {
...
```
After that, your new nexmo route will be available in the REST call.

If you have further questions, please ask.

2017-10-13 11:16 UTC, abdullateef97 commented
everything shd be in the readme file

2017-10-13 11:18 UTC, mjrdnk commented
Yes, this use case (nexmo) is so specific that it's place should be in the README examples section. However it would be the best to have some more generic example, but I will accept it anyway.

2017-10-13 11:53 UTC, abdullateef97 commented
@mjrdnk i believe my new commit should meet your specs

2017-10-13 11:58 UTC, mjrdnk approved these changes
Good Job, thanks for your awesome contribution! How would you use this endpoint /sms? Send sms as the body?

2017-10-13 11:58 UTC, merged

2017-10-13 12:00 UTC, mjrdnk commented
Just saw that markup is broken after merging. Please fix.

2017-10-13 14:14 UTC, abdullateef97 commented
can u specify what part

2017-10-13 18:31 UTC, mjrdnk commented
I fixed it already. Thanks for your contribution 😊